version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - 27017:27017

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-container
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
